apiVersion: v1
kind: Secret
metadata:
  name: mimir-basicauth
type: Opaque
stringData:
  username:
  password:
---
apiVersion: v1
kind: Secret
metadata:
  name: unifi-auth
type: Opaque
stringData:
  password: